apiVersion: v1
kind: Service
metadata:
  name: preprocess-app-service
spec:
  selector:
    app: preprocess-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8002
  type: LoadBalancer
