apiVersion: apps/v1
kind: Deployment
metadata:
  name: news-crawler-deployment
  labels:
    app: news-crawler
spec:
  # replicas: 2
  selector:
    matchLabels:
      app: news-crawler
  template:
    metadata:
      labels:
        app: news-crawler
    spec:
      containers:
      - name: news-crawler
        image: leesy010504/news-crawler:27
        ports:
        - containerPort: 8001
        resources:
          # limits:
          #   memory: "512Mi"
          #   cpu: "500m"
          # requests:
          #   memory: "256Mi"
          #   cpu: "250m"
          limits:
            memory: "2Gi"  # 2 Gigabytes of memory
            cpu: "2000m"   # 2 CPUs (2000 millicores)
          requests:
            memory: "1Gi"  # 1 Gigabyte of memory
            cpu: "1000m"   # 1 CPU (1000 millicores)
