# apiVersion: v1
# kind: Service
# metadata:
#   name: modeling-app-service
# spec:
#   type: LoadBalancer
#   selector:
#     app: modeling-app
#   ports:
#     - protocol: TCP
#       port: 80
#       targetPort: 8003
apiVersion: v1
kind: Service
metadata:
  name: modeling-app-service
  namespace: dev # Specify your namespace if needed
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: external
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
    service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
spec:
  type: LoadBalancer
  selector:
    app: modeling-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8003
